//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotelkamer_effect
    {
        public string Naam { get; set; }
        public string Type { get; set; }
        public string Eigenschap { get; set; }
        public string Operator { get; set; }
        public string Value { get; set; }
    
        public virtual Hotelkamer_type Hotelkamer_type { get; set; }
    }
}
