//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Prog6Entities : DbContext
    {
        public Prog6Entities()
            : base("name=Prog6Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Hotelkamer> Hotelkamers { get; set; }
        public virtual DbSet<Hotelkamer_effect> Hotelkamer_effect { get; set; }
        public virtual DbSet<Hotelkamer_type> Hotelkamer_type { get; set; }
        public virtual DbSet<Tamagotchi> Tamagotchis { get; set; }
    }
}
