//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tamagotchi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tamagotchi()
        {
            this.Hotelkamers = new HashSet<Hotelkamer>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public int Leeftijd { get; set; }
        public int Centjes { get; set; }
        public int Level { get; set; }
        public int Gezondheid { get; set; }
        public int Verveling { get; set; }
        public byte Levend { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotelkamer> Hotelkamers { get; set; }
    }
}
